### ISSUE TITLE
Mistake django-xxx with Django when checking for latest release

### ISSUE THREAD

**Issue by hongquan** [ninoseki/vscode-mogami#23]
I have a Django-based project, with many `django-xxx` extensions.

![image](https://github.com/ninoseki/vscode-mogami/assets/314607/f8d59133-b3f7-431f-93ed-13ad43dbac98)

When checking for latest release, Mogami returns the result of Django instead.

**Comment by ninoseki** [comment]
Could you provide `pyproject.toml` which can reproduce the issue, please?
Cause I cannot reproduce your claim.

<img width="354" alt="Screenshot 2024-05-19 at 13 08 02" src="https://github.com/ninoseki/vscode-mogami/assets/291028/9db1a0b6-4808-42a9-9274-67a7cd01a5cb">
<img width="428" alt="Screenshot 2024-05-19 at 13 08 08" src="https://github.com/ninoseki/vscode-mogami/assets/291028/bdb2b5da-622e-4c7c-8942-b8feb9ad10ad">

**Comment by ninoseki** [comment]
Never mind. I can reproduce the issue by randomly change the order. Let me check it.
