### ISSUE TITLE
Add Pixi support

### ISSUE THREAD

**Issue by elliotwaite** [ninoseki/vscode-mogami#75]
It would be great if this tool also supported [Pixi](https://pixi.sh/latest/) by being able to check for the latest versions of Conda dependencies listed under `[tool.pixi.dependencies]` in `pyproject.toml` files. More info about Pixi's `pyproject.toml` configuration options can be found here: https://pixi.sh/latest/advanced/pyproject_toml/

**Comment by elliotwaite** [comment]
Thanks for adding this so quickly! Looking forward to trying it when the next version is released.

**Comment by elliotwaite** [comment]
Just tested out v0.0.30 of the extension and the update works great. Thanks again!

**Comment by elliotwaite** [comment]
One thing to note for others using this tool is that it looks like even for the Conda dependencies, the latest listed versions are from PyPI. So if you update a Conda dependency to the latest listed version, you may get an error if that latest version isn't yet available on any of the Conda channels specified in your `pyproject.toml` file. For example, at the moment of writing this, the latest available version of uvicorn is:
* [uvicorn 0.30.5 on PyPI](https://pypi.org/project/uvicorn/)
* [uvicorn 0.30.4 on the conda-forge channel](https://anaconda.org/conda-forge/uvicorn)

One potential optimization would be to list both the PyPI latest version and the Conda latest version if they are different, but if only one of those is shown, I think I prefer it the way it is now, with it showing the PyPI version, since it seems like it's common for PyPI versions to be released before Conda versions. And then if I get an error while trying to install the latest version, like `No candidates were found for uvicorn ==0.30.5`, I'll know that the Conda version is currently behind the PyPI version, which can be helpful to know especially if the maintainers of a package stop releasing Conda versions and the latest Conda version becomes far behind the latest PyPI version.

**Comment by ninoseki** [comment]
Hmm, to be honest, it's my first time to know Conda/Anaconda has another ecosystem. 

It looks like the Anaconda package repository has a namespace (= username) according to [this SO answer](https://stackoverflow.com/a/77366340).
But is it okay to think most of packages are in `conda-forge` namespace? Do you know that by any chance?

**Comment by elliotwaite** [comment]
I think `conda-forge` is the most popular channel, but you can get the specific channels that should be checked for each dependency from the `pyproject.toml` file. For example:
```
[tool.pixi.project]
channels = ["conda-forge", "my-channel"]
```
Dependecies can also specify specific channels to use for that dependency. For example:
```
[tool.pixi.dependencies]
packgex = { version = "*", channel = "my-channel" }
```
The logic that Pixi uses to determine which channels should be checked for each dependency is described [here](https://pixi.sh/latest/advanced/channel_priority/) . But in those docs, they use the `pixi.toml` options format instead of the `pyproject.toml` format, so they are missing the `tool.pixi.` prefix. For example, `[project]` in `pixi.toml` would be `[tool.pixi.project]` in `pyproject.toml`.

**Comment by ninoseki** [comment]
Thanks for the explanation.
I will push a change to add a basic support for Anaconda (#78) which only supports the Anaconda package repository and `conda-forge` channel. (multiple channels and multiple repositories are not supported). Supporting those will be a backlog.

**Comment by elliotwaite** [comment]
That seems like a good start and should cover the common use case.

However, would it be possible to add an option to keep the current behavior of checking the Conda packages against PyPI? I think this option could be useful in the following situations:
* When you want to know if the Conda version is behind the PyPI version.
* When using non-conda-forge channels, since sometimes the PyPI latest version will be more aligned with the non-conda-forge channel's latest version than the conda-forge channel's latest version. For example, PyTorch uses the Conda channel `pytorch`, which has a latest version of `2.4.0` (as can be seen when you select the "Conda" package option [here](https://pytorch.org/get-started/locally/#start-locally)). This aligns with the latest version of [PyTorch on PyPI](https://pypi.org/project/torch/). However, the latest version of [PyTorch on `conda-forge`](https://anaconda.org/conda-forge/pytorch/) is `2.3.1`.
