### ISSUE TITLE
Support index and extra index URLs

### ISSUE THREAD

**Issue by MattTheCuber** [ninoseki/vscode-mogami#80]
### Clear and concise description of the feature request

It would great if we could specify the index-url and possible extra-index-urls in the settings as well as trusted hosts that way we can make this behave like a `pip.conf` file:

```
[global]
trusted-host = gitlab.company.local
index-url = https://gitlab.company.local/api/v4/groups/33/-/packages/pypi/simple
```

It could also just support using the global and local `pip.conf` files.

**Comment by ninoseki** [comment]
`--index-url` in `requirements.txt` is already supported. Also `tool.poetry.source` is supported.

`pip conf` can be vary (see https://pip.pypa.io/en/stable/cli/pip_config/) and I think it's good to make index URL explicit. I mean setting it in `requirements.txt` is better.

**Comment by MattTheCuber** [comment]
Oh, I didn't even realize that. Thanks!

**Comment by ninoseki** [comment]
FYI, I was unable to find the official one within a second but, you can do it like https://jfrog.com/help/r/jfrog-artifactory-documentation/use-a-pip-requirements-file.
