### ISSUE TITLE
Support for PEP 735 Dependency Groups

### ISSUE THREAD

**Issue by jorenham** [ninoseki/vscode-mogami#91]
### Clear and concise description of the feature request

UV recently added support for [PEP 735]https://peps.python.org/pep-0735/) `[dependency-groups]`, which is now the recommended way for [defining development dependencies](https://docs.astral.sh/uv/concepts/dependencies/#development-dependencies).

Currently, CodeLens only shows up if the dependency has no version restriction.
It would help if this would also work for the other deps 🙂

### Additional context

![image](https://github.com/user-attachments/assets/4f1db196-52de-455e-ab2d-8695bd1735a0)

**Comment by ninoseki** [comment]
Thanks for the heads up. The latest version will support it.
(Now it's being reviewed in VS Code Extension Marketplace)
